theme: jekyll-theme-minimal
title: The title of the website shows here
description: A rapid description of the website content
menu: [
{'name': 'Introduction & Purpose', 'pagename': 'index'},
{'name': 'Methodology & Design', 'pagename': 'page1'},
{'name': 'Data', 'pagename': 'page2'},
{'name': 'Discussion', 'pagename': 'page3'},
{'name': 'Limitations & Further Research', 'pagename': 'page4'},
{'name': 'Conclusion', 'pagename': 'page5'},
]
