theme: jekyll-theme-dinky
title: The 2018 Italian Elections
description: Which topics dominated digital public discourse in 2018 Italian Elections?
menu: [
{'name': 'Introduction', 'pagename': 'index'},
{'name': 'Methodology & Research Design', 'pagename': 'page1'},
{'name': 'Data', 'pagename': 'page2'},
{'name': 'Discussion', 'pagename': 'page3'},
{'name': 'Limitations & Further Research', 'pagename': 'page4'},
{'name': 'Conclusion', 'pagename': 'page5'},
]
